@startuml
actor Użytkownik
actor Administrator

Użytkownik -- (Generowanie raportów i backupu)
Użytkownik -- (Eksport raportu do pliku)
Użytkownik -- (Pobieranie dokumentacji technicznej)

Administrator -- (Ustawianie raportów)
Administrator -- (Akceptacja raportu)
Administrator -- (Generowanie dokumentacji technicznej)
Administrator -- (Określenie formatów plików dostarczanych przez system)

@enduml
