@startuml
actor Użytkownik
actor Administrator

Administrator -- (Przypisanie uprawnień/roli użytkownikowi do źródła danych)
Użytkownik -- (Rejestracja organizacji)
Administrator -- (Weryfikacja organizacji)
Administrator -- (Usuwanie organizacji)
Administrator -- (Modyfikacja organizacji)

@enduml
