@startuml
agent "CF0001 - Łączenie danych z różnych źródeł" 
agent "CF0002 - Automatyczna weryfikacja metadanych"
agent "CF0003 - Rejestracja i aktualizacja informacji o źródłach danych"
agent "CF0004 - Generowanie raportów i backupów"
agent "CF0005 - Zarządzanie uprawnieniami"
agent "CF0006 - Wizualizacja danych"
agent "CF0007 - Możliwość oceny danych"
agent "CF0008 - Integracja z CKAN"
agent "CF0009 - Udostępnienie interfejsu programistycznego (API)"
agent "CF0010 - Rejestracja działań użytkowników"
agent "CF0011 - Automatyzacja rejestracji firm"
agent "CF0012 - Dostęp do formularza rejestracji sprawdzającego dane w KRS"
agent "CF0013 - Zgłaszanie problemów"
agent "CF0014 - Szyfrowanie danych osobowych"
agent "CF0015 - Zabezpieczenia przed atakami na system/dane"
agent "CF0016 - Diagnostyka i monitorowanie stanu systemu"
agent "CF0017 - Wersja na telefon dla użytkowników, na komputer dla pracowników"
agent "CF0018 - Dostępność wielu wersji językowych"
@enduml