@startuml Monitorowanie i zabezpieczenia systemu

actor "Administrator" as Admin

usecase "PU043: Wyświetlenie stanu systemu i serwerów" as UC1
usecase "PU044: Tworzenie backupu systemu" as UC2
usecase "PU045: Odtwarzanie danych z backupu" as UC3
usecase "PU011: Wyświetlenie listy metadanych" as UC4
usecase "PU015: Wyszukanie metadanych" as UC5
usecase "PU046: Wyświetlenie historii zmian dokonanych w metadanych" as UC6

Admin -- UC1
Admin -- UC2
UC2 <-- UC3 : extend

Admin -- UC4
UC4 <-- UC5 : extend
UC5 <-- UC6 : extend

@enduml
