@startuml Zarządzanie użytkownikami i dostępem

actor "Administrator" as Admin
actor "Użytkownik" as User

usecase "PU001: Wyświetlenie listy użytkowników" as UC1
usecase "PU002: Przypisanie uprawnień/roli użytkownikowi do metadanych" as UC2
usecase "PU003: Zmiana uprawnień" as UC3
usecase "PU004: Rejestracja w systemie" as UC4
usecase "PU005: Logowanie do systemu" as UC5
usecase "PU006: Nadanie hasła" as UC6
usecase "PU007: Zmiana hasła" as UC7
usecase "PU008: Usunięcie konta" as UC8
usecase "PU009: Utworzenie konta" as UC9
usecase "PU010: Wylogowanie z systemu" as UC10

Admin -- UC1
UC1 <-- UC6 : extend
UC1 <-- UC2 : extend
UC2 <-- UC3 : extend
UC1 <-- UC8 : extend
UC1 <-- UC9 : extend

User -- UC4
User -- UC5
User -- UC7
User -- UC10  

@enduml

