@startuml
top to bottom direction
skinparam wrapWidth 100
skinparam usecaseWidth 150

actor "Użytkownik" as user
actor "Administrator" as admin

user -- (Logowanie do systemu)
user -- (Rejestracja do systemu)
user -- (Edycja profilu użytkownika)
user -- (Zmiana hasła)
user -- (Nadanie hasła)
user -- (Wyszukanie konta)

admin -- (Utworzenie konta)
admin -- (Usunięcie konta użytkownika)
admin -- (Nadanie uprawnień dla pracowników)
admin -- (Zmiana uprawnień nadanych wcześniej)
admin -- (Monitorowanie prób logowania użytkownika)
admin -- (Blokowanie możliwości logowania po 5 nieudanych próbach)

@enduml