@startuml Zarządzanie błędami i jakością danych

actor "Administrator" as Admin
actor "Użytkownik" as User

usecase "PU030: Wyświetlenie listy zgłoszeń użytkowników" as UC1
usecase "PU031: Generowanie raportów o zgłoszeniach użytkowników" as UC2
usecase "PU032: Wyświetlenie listy zarchiwizowanych raportów" as UC3
usecase "PU033: Wyświetlenie informacji o zgłoszeniu" as UC4
usecase "PU034: Odrzucenie zgłoszenia użytkownika" as UC5
usecase "PU035: Przyjęcie zgłoszenia użytkownika" as UC6
usecase "PU011: Wyświetlenie listy metadanych" as UC7
usecase "PU015: Wyszukanie metadanych" as UC8
usecase "PU019: Wyświetlenie informacji o metadanych" as UC9
usecase "PU036: Przegląd ocen jakości metadanych" as UC10
usecase "PU037: Zgłaszanie błędów i problemów z metadanymi" as UC11
usecase "PU038: Nadanie oceny jakości metadanymh" as UC12

Admin -- UC1
UC1 <-- UC2 : extend
UC1 <-- UC3 : extend

UC4 <-- UC5 : extend
UC4 <-- UC6 : extend
UC1 <-- UC4 : extend

User -- UC7
UC7 <-- UC8 : extend
UC8 <-- UC9 : extend
UC9 <-- UC10 : extend
UC10 <-- UC11 : extend
UC9 <-- UC12 : extend

@enduml
