@startuml Generowanie raportów i analiz

actor "Administrator" as Admin
actor "Użytkownik" as User

usecase "Wyświetlenie listy zgłoszeń użytkowników" as UC1
usecase "Generowanie raportów o zgłoszeniach użytkowników" as UC2
usecase "Eksport raportu do pliku PDF/CSV" as UC3
usecase "Archiwizacja raportu" as UC4
usecase "Wyświetlenie listy zarchiwizowanych raportów" as UC5
usecase "Wyświetlenie listy źródeł" as UC6
usecase "Wyświetlenie listy źródeł" as UC6user
usecase "Generowanie raportów o metadanych" as UC7
usecase "Wyświetlenie informacji o źródle danych" as UC8
usecase "Wyszukanie źródła danych" as UC9
usecase "Generowanie plików w formacie RDF" as UC10

Admin -- UC1
UC1 <-- UC2 : extend
UC2 <-- UC3 : extend
UC2 <-- UC4 : extend
UC4 <-- UC5 : extend

Admin -- UC6
UC6 <-- UC7 : extend

User -- UC6user
UC6user <-- UC9 : extend
UC9 <-- UC8 : extend
UC8 <-- UC10 : extend

@enduml
