@startuml Zarządzanie źródłami danych i metadanymi

actor "Administrator" as Admin

usecase "PU011: Wyświetlenie listy metadanych" as UC1
usecase "PU012: Eksport listy metadanych do pliku" as UC2
usecase "PU013: Rejestracja metadanych" as UC3
usecase "PU014: Dodanie nowego zestawu metadanych" as UC3a
usecase "PU015: Wyszukanie metadanych" as UC4
usecase "PU016: Archiwizacja metadanych" as UC5
usecase "PU017: Zlecenie automatycznej kontroli poprawności metadanych" as UC6
usecase "PU018: Usunięcie metadanych" as UC7
usecase "PU019: Wyświetlenie informacji o metadanych" as UC8
usecase "PU020: Pobranie szczegółowych informacji o metadanych" as UC9
usecase "PU021: Edycja metadanych" as UC10
usecase "PU022: Zagregowanie metadanych" as UC11
usecase "PU023: Walidacja poprawności metadanych" as UC12
usecase "PU024: Sprawdzanie kompletności danych w źródle" as UC13
usecase "PU025: Identyfikacja nieaktualnych metadanych" as UC14
usecase "PU026: Weryfikacja zgodności metadanych z systemem CKAN" as UC15

Admin -- UC1
UC1 <-- UC2 : extend
UC1 <-- UC3 : extend
UC3 --> UC3a : include

UC1 <-- UC4 : extend
UC4 <-- UC5 : extend
UC4 <-- UC6 : extend
UC4 <-- UC7 : extend
UC4 <-- UC8 : extend

UC8 <-- UC9 : extend
UC8 <-- UC12 : extend
UC8 <-- UC10 : extend
UC8 <-- UC11 : extend

UC12 --> UC13 : include
UC12 --> UC14 : include
UC12 <-- UC15 : extend

@enduml
