@startuml Zarządzanie źródłami danych i metadanymi

actor "Administrator" as Admin

usecase "Wyświetlenie listy źródeł" as UC1
usecase "Eksport listy źródeł do pliku" as UC2
usecase "Rejestracja nowego źródła danych" as UC3
usecase "Dodanie nowego zestawu metadanych" as UC3a
usecase "Wyszukanie źródła danych" as UC4
usecase "Archiwizacja źródeł danych" as UC5
usecase "Zlecenie automatycznej kontroli poprawności źródła danych" as UC6
usecase "Usunięcie źródła danych" as UC7
usecase "Wyświetlenie informacji o źródle danych" as UC8
usecase "Pobranie szczegółowych informacji o źródle danych" as UC9
usecase "Edycja metadanych" as UC10
usecase "Zagregowanie metadanych" as UC11
usecase "Walidacja poprawności metadanych" as UC12
usecase "Sprawdzanie kompletności danych w źródle" as UC13
usecase "Identyfikacja nieaktualnych metadanych" as UC14
usecase "Weryfikacja zgodności źródła z systemem CKAN" as UC15

Admin -- UC1
UC1 <-- UC2 : extend
UC1 <-- UC3 : extend
UC3 --> UC3a : include

UC1 <-- UC4 : extend
UC4 <-- UC5 : extend
UC4 <-- UC6 : extend
UC4 <-- UC7 : extend
UC4 <-- UC8 : extend

UC8 <-- UC9 : extend
UC8 <-- UC12 : extend
UC8 <-- UC10 : extend
UC8 <-- UC11 : extend

UC12 --> UC13 : include
UC12 --> UC14 : include
UC12 <-- UC15 : extend

@enduml
