@startuml
actor Użytkownik
actor Administrator

Użytkownik -- (Zgłoszenie błędów)
Użytkownik -- (Zgłoszenie problemu przez użytkownika)

Administrator -- (Przyjęcie zgłoszenia)
Administrator -- (Zamknięcie zgłoszenia)

@enduml
